apiVersion: v1
kind: Namespace
metadata:
  name: go-namespace
  labels:
    name: go-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-test
  namespace: go-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-test
  template:
    metadata:
      labels:
        app: go-api-test
    spec:
      containers:
        - name: go-api-test
          image: owcastillos/go-api-test:latest
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-test
  namespace: go-namespace
spec:
  ports:
  - port: 80
    targetPort: 3200
    name: http
  selector:
    app: go-api-test